name = "apollo-cloudflare-api"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "apollo-cloudflare-db"
database_id = "c370ca69-c11d-4d00-9fd0-b7339850fd30" # wrangler d1 create実行後に置き換え
migrations_dir = "migrations"

# 環境変数（開発環境）
[vars]
ENVIRONMENT = "development"

# workers.devドメインを無効化（カスタムドメイン設定後）
# workers_dev = false

# 本番環境設定
[env.production]
name = "apollo-cloudflare-api-prod"
vars = { ENVIRONMENT = "production" }

# 開発サーバー設定
[dev]
port = 8787
local_protocol = "http"

# ビルド設定
# [build]
# command = "pnpm run build"

# TypeScript設定はtsconfig.jsonで管理

# カスタムドメイン設定（例）
# route = { pattern = "api.yourdomain.com/*", zone_name = "yourdomain.com" }
# または
# routes = [
#   { pattern = "api.yourdomain.com/*", zone_name = "yourdomain.com" }
# ]